name:                warp-blog
version:             0.1.0.0
github:              "githubuser/warp-blog"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/warp-blog#readme>

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- blaze-builder
- http-types
- utf8-string
- postgresql-simple
- cryptonite
- bytestring
- directory
- wai-extra
- containers
- postgresql-simple-migration == 0.1.15.0
- file-embed
- random
- aeson
- text

library:
  source-dirs: src

executables:
  warp-blog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - warp-blog

tests:
  warp-blog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - warp-blog
